### ISSUE TITLE
Adding contributors to all contributors section of readme

### ISSUE THREAD

**Issue by vinaykakkad** [vinaykakkad/DIM#4]
Comment on this issue asking @all-contributors to add a contributor:
```bash
@all-contributors please add @<username> for <contributions>
```
Check the list of [contribution types](https://allcontributors.org/docs/en/emoji-key)

**Comment by YashLongani29** [comment]
@all-contributors please add @YashLongani29  for code

**Comment by Hirmay** [comment]
@all-contributors please add @Hirmay for code
